language: c
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test

branches:
  only:
    - master

install:
  - bash -x devtools/travis-ci/install.sh
  - export PYTHONUNBUFFERED=true
  - export PATH=$HOME/miniconda/bin:$PATH

script:
  # Create a test environment
  - conda create --yes -n test python=$python
  # Activate the test environment
  - source activate test
  # Add org channel
  - conda config --add channels ${ORGNAME}
  # Build recipie
  - conda build devtools/conda-recipe
  # Install locally-built package
  - conda install --yes --use-local ${PACKAGENAME}-dev
  - conda install --yes --quiet pip nose nose-timer
  # Test the package
  - cd devtools && nosetests $PACKAGENAME --nocapture --verbosity=2 --with-doctest --with-timer && cd ..

env:
  matrix:
    - python=2.7  CONDA_PY=27
    - python=3.4  CONDA_PY=34
    - python=3.5  CONDA_PY=35
    - python=3.6  CONDA_PY=36

  global:
    - ORGNAME="conda-forge"
    - PACKAGENAME="pymbar"
    # encrypted BINSTAR_TOKEN for push of dev package to binstar
    - secure: "TCAT3UIHKGb2yndGXrjLILFZggGjVL//apC48YQTQqqHDj+PNFnmYw6GeVfiGLKYMG74aiTgOPxVUjsY73CdXCp/u76cscq4h5htIo3ed1gcsmfK1MTZxKx7xrdTJa3Qedc8QbpPhV9RhagoCEFNQj1TWyeDKQPv8nFcufZsELo="

after_success:
  - echo "after_success"
  - if [ "$TRAVIS_SECURE_ENV_VARS" == true ]; then source devtools/travis-ci/after_success.sh; fi
