package:
  name: pymbar-dev
  version: !!str 3.0.3.dev0

source:
  path: ../../

requirements:
  build:
    - python
    - setuptools
    - six
    - numpy x.x
    - toolchain
  run:
    - python
    - numpy x.x
    - scipy
    - numexpr
    - six

test:
  requires:
    - nose
    - statsmodels
  imports:
    - pymbar
  commands:
    - nosetests pymbar --with-doctest --doctest-tests -v

about:
  home: https://github.com/choderalab/pymbar
  license: MIT
  summary: Python implementation of the multistate Bennett acceptance ratio (MBAR) method.
